name: build and deploy to docker hub
on:
  [workflow_dispatch]

jobs: 
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build ./api/ -t helouich/qr-code-api:latest

      - name: Push Docker image
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u helouich --password-stdin
          docker push helouich/qr-code-api:latest
