name: build and deploy to docker hub
on:
  [workflow_dispatch]

jobs: 
  publish_images :
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build docker image
        run: docker build ./api/ -t helouich/qr-code-api:latest
      - name: push docker image
        run: |
         docker login -u helouich -p ${{ secrets.DOCKER_HUB_TOKEN }} 
         docker push helouich/qr-code-api:latest